### PR TITLE
support for commonjs \ webpack

### PR DESCRIPTION
**Pull request by dokkis**
Please add support for commonjs introducing a index.js file and changing the main file to index.js into the package.js.

With webpack I am unable to import smoothly the angular-restheart library. In order to do it, I singularly import all the required js because of:

1) It's not requirejs compliant
2) in the NPM repository, the dist folder missed

I added a index.js which defines all the requires of the js composed the library.

Thank you :)

### CODE REVIEW

**Comment by mkjsix** [comment]
Same here @RickyGeek we need to test and then we'll release the new version. In case I'll take care of this myself as soon as possible.

**Comment by dokkis** [comment]
Thank you for integrating it.

Could you please write me here when you'll update the new version of the library into NPM repository?

Thank you ;)

**Comment by mkjsix** [comment]
@dokkis it's done. Please let us know if everything looks fine, thank you.

**Comment by dokkis** [comment]
@mkjsix I just updated the library and now everything seems fine. Now I am able to import the library using webpack without referencing all the JS files.

For the other issues, now the $state variable is not undefined anymore so I can correctly use the onUnauthenticated functionality :+1: 

Thank you for the fast answers! I sent also a pull request to Restangular in order to support the $oid inside the etag for MongoDB database but I suppose you are not involved in Restangular but you just use it.

For a project I am building a Generic Web Interface, built from JSON Schema, for RESTHeart backend using the project SchemaForm (schemaform.io), maybe you could interested on it.

If yes I could keep in touch and maybe publish the project on Github. Let me know ;)

**Pull request merged**
